name: my-environment
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - pip:
    - jupyter_contrib_nbextensions
    - nbgitpuller
    - sphinx-gallery
    - matplotlib
    - ipysheet
    - fileupload
    - pytz
    - python-dateutil
    - tqdm
    - telethon
    - asyncio